project:
  type: default
  resources:
    - "assets/*.svg"
    - "assets/*.js"

format:
  revealjs:
    theme: [default, theme.scss]
    slide-number: c/t
    progress: false
    controls: false
    navigation-mode: linear
    transition: slide
    transition-speed: slow
    background-transition: none
    width: 1280
    height: 800
    margin: 0
    min-scale: 0.2
    max-scale: 3.0
    center: false
    hash-type: number
    history: true
    html-math-method: katex
    embed-resources: false
    code-line-numbers: false
    highlight-style: breeze
    fig-align: center
    incremental: false
    auto-stretch: false
    include-after-body:
      text: |
        <script src="assets/inject-landmark.js" defer></script>
        <script src="assets/clicker.js" defer></script>
